name: student_activity_tracker
description: "A Flutter project for UTS Pemrograman Perangkat Bergerak."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.4.0
  provider: ^6.1.2 
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- TAMBAHKAN BAGIAN INI ---
  assets:
    # Daftarkan folder gambar Anda
    - assets/images/
  # -----------------------------